# Generated by Django 5.1.4 on 2025-01-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=255, unique=True)),
                ('stock_article', models.CharField(max_length=255, null=True, unique=True)),
                ('name', models.TextField()),
                ('gender', models.CharField(max_length=255, null=True)),
                ('main_image', models.TextField(null=True)),
                ('images_urls', models.JSONField(null=True)),
                ('description', models.TextField(null=True)),
                ('age_category', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(max_length=255)),
                ('material', models.CharField(max_length=255)),
                ('product_status', models.CharField(max_length=255)),
                ('product_type', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
