# Generated by Django 5.1.5 on 2025-01-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_full_name_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
